WIP: Backend setup
cerebro-iiitv/cerebro-web-2019 pull request #1
Opened 2019-01-24 15:39 UTC by Monal5031

2019-01-24 16:31 UTC, PiyushPawar17 commented on src/actions/authActions.js
> +    SIGN_IN_DONE: 'AUTH.SIGN_IN.DONE',
Keep key-value pair same like SIGN_IN_DONE = 'SIGN_IN_DONE' for all constants.

2019-01-24 16:34 UTC, piyush-pawar-17 requested changes

2019-01-24 16:34 UTC, PiyushPawar17 commented on src/actions/authActions.js
> +    SIGN_IN_DONE: 'AUTH.SIGN_IN.DONE',
Keep key-value pair same like SIGN_IN_DONE = 'SIGN_IN_DONE' for all constants.

2019-01-24 17:56 UTC, piyush-pawar-17 approved these changes

2019-01-24 17:59 UTC, anshumanv commented
Deploy fail ka dekh le

2019-01-27 14:26 UTC, Monal5031 commented
@anshumanv Apologies for late updates done with PR (backend setup now)

PS: Don't look at UI there is no CSS atm

2019-01-27 16:19 UTC, anshumanv approved these changes

2019-01-27 17:11 UTC, merged