Add Timeline Page
cerebro-iiitv/cerebro-web-2019 pull request #5
Opened 2019-02-05 05:54 UTC by samagragupta

2019-02-05 10:12 UTC, anshumanv reviewed
Quick deploy link needed.

2019-02-05 10:12 UTC, anshumanv commented on src/components/EventTimeline.js
> +const hStyle = {
Move all styling to sass

2019-02-05 18:45 UTC, samagragupta commented on src/components/EventTimeline.js
> +const hStyle = {
Done

2019-02-05 18:58 UTC, samagragupta commented
http://chai-sutta.surge.sh/timeline

2019-02-06 04:08 UTC, rossoskull requested changes
* Timeline card body's font size is very small
* Change the date format

2019-02-06 06:35 UTC, samagragupta commented
Done the changes @anshumanv @rossoskull

2019-02-12 14:51 UTC, rossoskull commented
Provide a preview link

2019-02-13 08:28 UTC, anshumanv commented
Update

2019-02-15 17:47 UTC, aashutoshrathi commented
Surge krdo franz

2019-02-16 04:46 UTC, samagragupta commented
@aashutoshrathi @anshumanv http://alike-competition.surge.sh/timeline

2019-02-16 05:01 UTC, aashutoshrathi commented
Looks good, please resolve conflicts and update your dev branch

2019-02-16 05:01 UTC, aashutoshrathi approved these changes
Merge after conflicts resolved.

2019-02-16 05:51 UTC, samagragupta commented
@aashutoshrathi Done

2019-02-16 06:01 UTC, aashutoshrathi commented
@samagragupta one more surge link

2019-02-16 06:52 UTC, anshumanv commented
😕

2019-02-16 06:52 UTC, merged

2019-02-16 09:21 UTC, anshumanv commented
Code quality badha thoda